### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by Avakining** [EDToaster/beehive-tooltips#9]
If you have the time, could you please update to 1.19? Thank you

**Comment by JackWolfard** [comment]
Hi @Avakining, I updated the mod to 1.19.2. If you want to help test it, view my PR #10.

**Comment by EGOIST1372** [comment]
@EDToaster Hi
your 1.19.2 version works in 1.19.3 so you can add the 1.19.3 tag in curseforge
also this issue should be closed long time ago :D
